### PR TITLE
fix: Fixed scope cancellation that leads to bug when invalidating composable doesn't invalidate cluster

### LINKED ISSUE #537: Marker is not updating when it's getting recomposed
When markerContent or clusterContent is being recomposed, marker does not update it's appearance

### PR DESCRIPTION
**Pull request by y9san9**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #537 🦕

### CODE REVIEW

**Comment by pioPirrung** [comment]
@dkhawk any updates here? This also seems to fix an issue related to canceling the image loader of coil. I think multiple people are interested in this fix

Issues: #210 #385 #542

**Comment by patrickcapadmi** [comment]
Is there any movement on this PR? We'd quite like to get this fix in to help images load in more reliably.

**Comment by huanghaieeee** [comment]
朋友
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "googlemaps/android-maps-compose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月15日(星期一) 晚上7:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [googlemaps/android-maps-compose] fix(close #537): Fixed scope cancellation that leads to bug when invalidating composable doesn't invalidate marker/cluster (PR #538)





 
By the way, my case was also image loading :)
 But I have some other questions regarding how builtin clustering works, so I just copied the code and made my modifications

**Comment by pioPirrung** [comment]
Thanks for your reply @kikoso. I did not tried it with plain `MarkerComposable`. For me (and I think the PR only targets `Clustering`) the fix works under the circumstance while using a `Cluster`. 

<details>
  <summary>Code Snippet</summary>

```kt
@OptIn(MapsComposeExperimentalApi::class)
@Composable
fun TestMapScreen() {
    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(LatLng(49.897288, 10.8783964), 7f)
    }

    Box(
        modifier = Modifier.fillMaxSize()
    ) {
        GoogleMap(
            modifier = Modifier
                .fillMaxSize(),
            onMapLoaded = { },
            cameraPositionState = cameraPositionState,
            uiSettings = MapUiSettings(
                myLocationButtonEnabled = false,
                mapToolbarEnabled = false,
                zoomControlsEnabled = false
            )
        ) {
            val configuration = LocalConfiguration.current
            val screenHeight = configuration.screenHeightDp.dp
            val screenWidth = configuration.screenWidthDp.dp
            val clusterManager = rememberClusterManager<MyItem>()
            clusterManager?.setAlgorithm(
                NonHierarchicalViewBasedAlgorithm(
                    screenWidth.value.toInt(),
                    screenHeight.value.toInt()
                )
            )
            val renderer = rememberClusterRenderer(
                clusterContent = { cluster ->
                    MyItemClusterContent(
                        modifier = Modifier
                            .size(30.dp, 38.dp)
                            .clip(MarkerShape())
                            .background(
                                Color(
                                    red = 255,
                                    green = 165,
                                    blue = 0
                                )
                            ),
                        cluster = cluster
                    )
                },
                clusterItemContent = { item ->
                    MyItemMarker(item)
                },
                clusterManager = clusterManager,
            )
            SideEffect {
                clusterManager ?: return@SideEffect
                clusterManager.setOnClusterItemClickListener {
                    true
                }
            }
            SideEffect {
                if (clusterManager?.renderer != renderer && renderer != null) {
                    (renderer as DefaultClusterRenderer).minClusterSize = 2
                    clusterManager?.renderer = renderer
                }
            }

            if (clusterManager != null) {
                Clustering(
                    items = previewData,
                    clusterManager = clusterManager,
                )
            }
        }
    }
}

@Composable
fun MyItemMarker(item: MyItem) {
    val context = LocalContext.current
    Column(
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Box(
            modifier = Modifier
                .size(30.dp, 38.dp)
                .clip(MarkerShape())
                .background(Color.Green),
        ) {
            AsyncImage(
                modifier = Modifier
                    .size(30.dp)
                    .padding(5.dp),
                model = ImageRequest.Builder(context)
                    .data(item.itemUrl)
                    .allowHardware(false)
                    .crossfade(false)
                    .error(R.drawable.placeholder)
                    .diskCacheKey(item.id)
                    .memoryCacheKey(item.id)
                    .fallback(R.drawable.placeholder)
                    .placeholder(R.drawable.placeholder)
                    .build(),
                contentDescription = null
            )
        }
        Column(
            modifier = Modifier.width(150.dp),
        ) {
            Text(
                modifier = Modifier.fillMaxWidth(),
                text = item.itemTitle,
                style = MaterialTheme.typography.labelSmall,
                textAlign = TextAlign.Center
            )
        }
    }
}

@Composable
fun MyItemClusterContent(
    modifier: Modifier = Modifier,
    cluster: Cluster<MyItem>
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Box(
            modifier = modifier
        ) {
            Text(
                modifier = Modifier
                    .padding(5.dp)
                    .fillMaxWidth(),
                text = "%,d".format(cluster.size),
                fontSize = 16.sp,
                fontWeight = FontWeight.Black,
                textAlign = TextAlign.Center
            )
        }
        Column(
            modifier = Modifier.width(130.dp),
        ) {
            Text(
                modifier = Modifier.fillMaxWidth(),
                text = cluster.items.stream().findFirst().get().title,
                style = MaterialTheme.typography.bodyMedium,
                textAlign = TextAlign.Center
            )
            Text(
                modifier = Modifier.fillMaxWidth(),
                text = "+${cluster.size - 1} more",
                style = MaterialTheme.typography.labelSmall,
                textAlign = TextAlign.Center
            )
        }
    }
}

data class MyItem(
    val id: String = UUID.randomUUID().toString(),
    val itemPosition: LatLng,
    val itemTitle: String,
    val itemUrl: String = "https://picsum.photos/200/300",
) : ClusterItem {
    override fun getPosition(): LatLng =
        itemPosition

    override fun getTitle(): String =
        itemTitle

    override fun getSnippet(): String? = null

    override fun getZIndex(): Float? = null
}

val markerMain = LatLng(49.89, 10.87)
val previewData = listOf(
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
    MyItem(
        itemPosition = LatLng(
            markerMain.latitude + Random.nextFloat(),
            markerMain.longitude + Random.nextFloat(),
        ),
        itemTitle = "Hello"
    ),
)
  ```
</details>

And here is also a video of proof.

https://github.com/googlemaps/android-maps-compose/assets/54797113/a8c04887-b96e-4d82-9943-a56f00b23077

**Comment by pioPirrung** [comment]
Hi @kikoso, thanks again for your really quick reply. Ah now I see, sorry for the confusion. Initially I thought that this PR would fix it for `MarkerComposable` and for `Clustering`, but this isn't the case, that's correct. So sorry for that!

**Comment by danprado** [comment]
Confirming this fix worked for me when trying to load an `AsyncImage` with Coil. **Note**: This fixes it for Clustering only. `MarkerComposable` is still broken.

**Comment by jialbanc** [comment]
This issue is still unfixed when using only MarkerComposable

**Pull request merged**
