### PR TITLE
chore: Update Compose libraries and Compiler.

### PR DESCRIPTION
**Pull request by arriolac**
Compose now supports independent versioning: https://android-developers.googleblog.com/2022/06/independent-versioning-of-Jetpack-Compose-libraries.html

* Updates compose compiler to the stable version (1.2.0)
* Updates compose libraries to the latest 1.2.0 rc (1.2.0-rc03)
* Updates target/compile SDK to 32

### CODE REVIEW

**Comment by barbeau** [comment]
Looks like Lint is now flagging an error in `Polygon.kt`:
https://github.com/googlemaps/android-maps-compose/runs/7285245949?check_suite_focus=true#step:5:445

>Lint found 1 error and 3 warnings. First failure:
/home/runner/work/android-maps-compose/android-maps-compose/maps-compose/src/main/java/com/google/maps/android/compose/Polygon.kt:79: Error: Call requires API level 24 (current min is 21): java.lang.Iterable#forEach [NewApi]
                holes.forEach {

Seems like it's this problem where it's using Java 8 `forEach` instead of Kotlin:
https://stackoverflow.com/a/44752239/937715

I can confirm if I change the code to:

```kotlin
                for (h in holes) {
                    addHole(h)
                }
```

...then running `./gradlew :maps-compose:lintDebug` I no longer get the lint error.

@arriolac Do you want to fix this issue in this PR or should we address it separately?

**Comment by arriolac** [comment]
Will address that in the same PR. Thanks @barbeau

**Comment by barbeau** [comment]
I think it's (at least) the same error still:
https://github.com/googlemaps/android-maps-compose/runs/7290216852?check_suite_focus=true#step:5:481


>Lint found 1 error and 3 warnings. First failure:
Fix the issues identified by lint, or add the following to your build script to proceed with errors:
/home/runner/work/android-maps-compose/android-maps-compose/maps-compose/src/main/java/com/google/maps/android/compose/Polygon.kt:79: Error: Call requires API level 24 (current min is 21): java.lang.Iterable#forEach [NewApi]
...
                holes.forEach { hole ->

Locally I tried:

```kotlin
                holes.forEach { hole ->
                    addHole(hole)
                }
```

...as well and got the same Lint error as the original code. The `for (h in holes) {` version works though - I didn't dig any further beyond that.

**Comment by arriolac** [comment]
@barbeau looks like some of the MapInColumnTests are failing on this version bump. Since this won't cut a release, should we go ahead and merge this and address the failing tests separately? I'll file an issue.

**Comment by barbeau** [comment]
@arriolac Agreed, let's merge this and address the test failures separately. FWIW, when running this PR locally all the tests pass. I saw test failures on CI in PR https://github.com/googlemaps/android-maps-compose/runs/7283340731 (even trying multiple runs) that also passed locally, although after the PR was merged CI passed. So it seems like the tests are a bit flaky in general.

**Review by barbeau — APPROVED** [review]
LGTM

**Comment by arriolac** [comment]
> @arriolac Agreed, let's merge this and address the test failures separately. FWIW, when running this PR locally all the tests pass. I saw test failures on CI in PR https://github.com/googlemaps/android-maps-compose/runs/7283340731 (even trying multiple runs) that also passed locally, although after the PR was merged CI passed. So it seems like the tests are a bit flaky in general.

Yeah it looks isolated to CI. I'm able to see tests pass locally as well

**Pull request merged**
