### PR TITLE
feat: customize MarkerInfoWindow's Marker using Composable

### LINKED ISSUE #383: Support Composable for MarkerInfoWindow
`Composable` content support has been added for `Marker`.
However, `MarkerInfoWindow` don't have this feature.

`MarkerInfoWindowComposable` needs to be created

Also, what's the difference between `MarkerInfoWindow` and `MarkerInfoWindowContent`?

### PR DESCRIPTION
**Pull request by mosmb**
Add `Composable` support for Marker inside `MakerInfoWindow`
---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #383  🦕

### CODE REVIEW

**Comment by mosmb** [comment]
hi @wangela 
any news for this one?

**Comment by mosmb** [comment]
Ooops completely forgot about this, will do ! @kikoso

**Comment by mosmb** [comment]
@kikoso 
Done, should be good now.
Do not hesitate if you have any feedbacks.
CLA check failed because I changed my GitHub name and forgot to submit a new one, it's done now.

**Comment by mosmb** [comment]
ping @kikoso

**Review by dkhawk — APPROVED** [review]

**Pull request merged**
