### PR TITLE
fix: Fix NoSuchElementException when rendering custom cluster content

### LINKED ISSUE #271: NoSuchElementException when setting Image composable in clusterContent
#### Environment details

1. compileSdkVersion 33, targetSdkVersion 32
2. OS Version on emulator - Api 33
3.  "com.google.maps.android:maps-compose:2.11.0" and "com.google.maps.android:maps-compose-utils:2.11.0"

#### Steps to reproduce

  1. Put an image in the clusterContent lambda in the `Clustering` composable. The items are in thousands.  See code example
  2. Run the app.   
  3. You will be able to see clusters.App crashes      
  4. Now zoom in more.
  5. App crashes.
  6. Set clusterContent = null, the the app doesn't crash on zooming in. 

#### Code example

```
  clusterContent = {
                    Image(
                        modifier = Modifier.wrapContentSize(),
                        painter = painterResource(
                            R.drawable.XYZ
                        ),
                        contentDescription = null,
                    )
                }
```

#### Stack trace

```

    java.util.NoSuchElementException: Collection contains no element matching the predicate.
                                                             	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.getDescriptorForCluster(ClusterRenderer.kt:234)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer.onBeforeClusterRendered(DefaultClusterRenderer.java:913)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1073)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2400(DefaultClusterRenderer.java:1021)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:738)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:707)
                                                             	
```

### PR DESCRIPTION
**Pull request by DSteve595**
This fixes a crash when rendering custom cluster content. It seems to be timing-related. T cluster renderer creates markers that aren't actually meant to be rendered, so we don't have an active ComposeView for it. This works around it by simply no-op'ing when that happens.

Fixes #271 🦕

### CODE REVIEW

**Comment by hbb20** [comment]
@DSteve595 This fixes the crash but shows default marker and cluster (for a few markers) for fraction of second when zoomed in/out quickly. 

How about following?

1. make `createAndAddView()` return the viewInfo
```kotlin
   private fun createAndAddView(key: ViewKey<T>): ViewInfo {
        val view = InvalidatingComposeView(
            context,
            content = when (key) {
                is ViewKey.Cluster -> {
                    { clusterContentState.value?.invoke(key.cluster) }
                }

                is ViewKey.Item -> {
                    { clusterItemContentState.value?.invoke(key.item) }
                }
            }
        )
        val renderHandle = viewRendererState.value.startRenderingView(view)
        scope.launch {
            collectInvalidationsAndRerender(key, view)
        }

        val viewInfo = ViewInfo(view, renderHandle)
        keysToViews[key] = viewInfo
        return viewInfo
    }
```

2.  Then these functions can be
```kotlin
   override fun getDescriptorForCluster(cluster: Cluster<T>): BitmapDescriptor {
        return if (clusterContentState.value != null) {
            val viewInfo = keysToViews.entries
                .firstOrNull { (key, _) -> (key as? ViewKey.Cluster)?.cluster == cluster }?.value
                ?: createAndAddView(ViewKey.Cluster(cluster))
            renderViewToBitmapDescriptor(viewInfo.view)
        } else {
            super.getDescriptorForCluster(cluster)
        }
    }

    override fun onBeforeClusterItemRendered(item: T, markerOptions: MarkerOptions) {
        super.onBeforeClusterItemRendered(item, markerOptions)
        if (clusterItemContentState.value != null) {
            val viewInfo = keysToViews.entries
                .firstOrNull { (key, _) -> (key as? ViewKey.Item)?.item == item }?.value
                ?: createAndAddView(ViewKey.Item(item))
            markerOptions.icon(renderViewToBitmapDescriptor(viewInfo.view))
        }
    }
```

**Comment by matsudamper** [comment]
My product did not show marker, but now with this code it shows up with no problems.
https://github.com/googlemaps/android-maps-compose/pull/280#issuecomment-1458993270

**Comment by DSteve595** [comment]
Agree that's a better fallback, thanks @hbb20. Updated.

**Review by wangela — APPROVED** [review]

**Comment by charlesbukenyaqvik** [comment]
I am now getting this with latest release, `FATAL EXCEPTION: main
                                                                                                    Process: no.ums.hrapp.stage, PID: 10773
                                                                                                    java.lang.IllegalArgumentException: Unmanaged descriptor
                                                                                                    	at com.google.maps.api.android.lib6.common.m.c(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):0)
                                                                                                    	at com.google.maps.api.android.lib6.impl.w.c(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):1)
                                                                                                    	at com.google.maps.api.android.lib6.impl.cy.u(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):2)
                                                                                                    	at com.google.android.gms.maps.model.internal.p.ba(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):42)
                                                                                                    	at fd.onTransact(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):4)
                                                                                                    	at android.os.Binder.transact(Binder.java:1164)
                                                                                                    	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
                                                                                                    	at com.google.android.gms.internal.maps.zzy.zzs(com.google.android.gms:play-services-maps@@18.1.0:3)
                                                                                                    	at com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms:play-services-maps@@18.1.0:2)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer.onClusterUpdated(DefaultClusterRenderer.java:972)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1091)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$1900(DefaultClusterRenderer.java:1027)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:738)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:710)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Pull request merged**
